language: node_js
node_js:
 - "node"

before_install:
- openssl aes-256-cbc -K $encrypted_0b101188e5d3_key -iv $encrypted_0b101188e5d3_iv -in travis.enc -out ~/.ssh/id_rsa -d
- npm install -g hexo-cli
- npm install
- hexo g

script: hexo d
